# Generated by Django 3.2.19 on 2023-05-07 17:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_fltno', models.CharField(default='KE0000', max_length=6, verbose_name='출발 편명')),
                ('r_fltno', models.CharField(default='KE0000', max_length=6, verbose_name='리턴 편명')),
                ('airline', models.CharField(blank=True, max_length=20, verbose_name='항공사')),
                ('price', models.IntegerField(default=0, help_text='미입력시 0. 문의', verbose_name='숫자')),
                ('d_city1', models.CharField(blank=True, default='ICN', max_length=3)),
                ('d_city2', models.CharField(blank=True, default='CJU', max_length=3)),
                ('d_date1', models.DateField(default=datetime.date(2000, 1, 1))),
                ('d_date2', models.DateField(default=datetime.date(2000, 1, 2))),
                ('d_daychange', models.IntegerField(default=1)),
                ('stay', models.IntegerField(default=5)),
                ('r_daychange', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='block.block')),
            ],
        ),
    ]
