# Generated by Django 3.2.19 on 2023-05-07 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockitem',
            name='name_fk',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='BlockItem',
        ),
    ]
