# Generated by Django 3.2.19 on 2023-05-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_block_blockitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(default='ICNDAD-KE000/KE111-3n5d(하계)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='blockitem',
            name='d_fltno',
            field=models.CharField(default='KE000', max_length=6, verbose_name='출발 편명'),
        ),
        migrations.AlterField(
            model_name='blockitem',
            name='r_fltno',
            field=models.CharField(default='KE000', max_length=6, verbose_name='리턴 편명'),
        ),
    ]
