# Generated by Django 3.2.19 on 2023-05-08 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0004_auto_20230508_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
