# Generated by Django 3.2.18 on 2023-04-15 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_touritem_d_city1'),
    ]

    operations = [
        migrations.AddField(
            model_name='touritem',
            name='d_city2',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='touritem',
            name='d_date1',
            field=models.DateField(default=datetime.datetime(2000, 1, 1, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='touritem',
            name='d_date2',
            field=models.DateField(default=datetime.datetime(2000, 1, 1, 1, 1)),
            preserve_default=False,
        ),
    ]
