# Generated by Django 3.2.18 on 2023-04-15 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_auto_20230415_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='touritem',
            name='d_time1',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
        migrations.AddField(
            model_name='touritem',
            name='d_time2',
            field=models.TimeField(default=datetime.time(23, 30)),
        ),
        migrations.AddField(
            model_name='touritem',
            name='r_city1',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='touritem',
            name='r_city2',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='touritem',
            name='d_date1',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='touritem',
            name='d_date2',
            field=models.DateField(default=datetime.date(2000, 1, 2)),
        ),
    ]
