# Generated by Django 3.2.18 on 2023-04-15 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_auto_20230415_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='touritem',
            name='d_daychange',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='touritem',
            name='r_daychange',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='touritem',
            name='r_time1',
            field=models.TimeField(default=datetime.time(23, 30)),
        ),
        migrations.AddField(
            model_name='touritem',
            name='r_time2',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
        migrations.AddField(
            model_name='touritem',
            name='stay',
            field=models.IntegerField(default=5),
        ),
    ]
