# Generated by Django 3.2.18 on 2023-04-15 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_auto_20230415_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touritem',
            name='d_date2',
        ),
    ]
