# Generated by Django 3.2.18 on 2023-04-15 20:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0006_remove_touritem_d_date2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tour',
            new_name='DetailCode',
        ),
    ]
