# Generated by Django 3.2.18 on 2023-04-15 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_rename_tour_detailcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailcode',
            name='detail_code',
            field=models.CharField(default=django.utils.timezone.now, help_text='예)KE01 : 중복불가', max_length=4, unique=True),
            preserve_default=False,
        ),
    ]
