# Generated by Django 3.2.18 on 2023-04-15 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0008_detailcode_detail_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basiccode',
            name='name',
        ),
        migrations.RemoveField(
            model_name='detailcode',
            name='author',
        ),
        migrations.RemoveField(
            model_name='detailcode',
            name='basic_code',
        ),
        migrations.RemoveField(
            model_name='detailcode',
            name='category',
        ),
        migrations.RemoveField(
            model_name='detailcode',
            name='content',
        ),
        migrations.RemoveField(
            model_name='detailcode',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='detailcode',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='detailcode',
            name='head_image',
        ),
        migrations.RemoveField(
            model_name='detailcode',
            name='hook_text',
        ),
        migrations.RemoveField(
            model_name='detailcode',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='detailcode',
            name='title',
        ),
        migrations.RemoveField(
            model_name='detailcode',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='basiccode',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basiccode',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.category'),
        ),
        migrations.AddField(
            model_name='basiccode',
            name='content',
            field=markdownx.models.MarkdownxField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basiccode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basiccode',
            name='detail_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.detailcode'),
        ),
        migrations.AddField(
            model_name='basiccode',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='tour/files/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='basiccode',
            name='head_image',
            field=models.ImageField(blank=True, upload_to='tour/images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='basiccode',
            name='hook_text',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='basiccode',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tour.Tag'),
        ),
        migrations.AddField(
            model_name='basiccode',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basiccode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='detailcode',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basiccode',
            name='basic_code',
            field=models.CharField(help_text='예)KE01 : 중복불가', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='detailcode',
            name='detail_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
