# Generated by Django 3.2.18 on 2023-04-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_auto_20230415_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailcode',
            old_name='baskci_code',
            new_name='basic_code',
        ),
    ]
