# Generated by Django 3.2.18 on 2023-04-15 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_rename_baskci_code_detailcode_basic_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiccode',
            name='basic_code',
            field=models.CharField(help_text='예)ATP101', max_length=6, unique=True, verbose_name='기초코드'),
        ),
        migrations.AlterField(
            model_name='basiccode',
            name='hook_text',
            field=models.CharField(blank=True, max_length=120, verbose_name='상품설명'),
        ),
        migrations.AlterField(
            model_name='basiccode',
            name='title',
            field=models.CharField(help_text='방콕/파타야 빠빠빠 상품', max_length=80, verbose_name='기초 상품 제목'),
        ),
        migrations.AlterField(
            model_name='detailcode',
            name='detail_code',
            field=models.CharField(help_text='예)KE00 항공+숫자로 작성', max_length=4, unique=True, verbose_name='상세코드'),
        ),
        migrations.AlterField(
            model_name='detailcode',
            name='title',
            field=models.CharField(max_length=50, verbose_name='의미없음'),
        ),
    ]
