# Generated by Django 3.2.18 on 2023-04-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0013_auto_20230415_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touritem',
            old_name='basic_code',
            new_name='item_code',
        ),
        migrations.AlterField(
            model_name='detailcode',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='의미없음'),
        ),
    ]
