# Generated by Django 3.2.18 on 2023-04-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0014_auto_20230415_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailcode',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='의미없음-메모용'),
        ),
    ]
