# Generated by Django 3.2.18 on 2023-04-20 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0016_auto_20230420_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='touritem',
            name='air_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='detailcode',
            name='detail_code',
            field=models.CharField(help_text='예)KE00 항공+숫자로 작성... 이건...TourItem에서 입력하는게 맞을 듯', max_length=4, unique=True, verbose_name='상세코드'),
        ),
        migrations.AlterField(
            model_name='touritem',
            name='airline',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='touritem',
            name='detail_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code', to='tour.detailcode'),
        ),
    ]
