# Generated by Django 3.2.18 on 2023-04-20 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0017_auto_20230420_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touritem',
            name='detail_code',
        ),
        migrations.AddField(
            model_name='touritem',
            name='basic_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code', to='tour.basiccode'),
        ),
        migrations.DeleteModel(
            name='DetailCode',
        ),
    ]
