# Generated by Django 3.2.18 on 2023-04-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0018_auto_20230420_0554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touritem',
            old_name='code_suffix',
            new_name='suffix_code',
        ),
        migrations.AlterField(
            model_name='touritem',
            name='air_code',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='touritem',
            name='airline',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
