# Generated by Django 3.2.18 on 2023-04-22 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0019_auto_20230420_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touritem',
            name='basic_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_item', to='tour.basiccode'),
        ),
    ]
