# Generated by Django 3.2.18 on 2023-04-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0021_iti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touritem',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
