# Generated by Django 3.2.18 on 2023-04-24 02:18

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0023_touritem_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touritem',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
