# Generated by Django 3.2.18 on 2023-04-24 03:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0024_alter_touritem_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touritem',
            name='content',
            field=tinymce.models.HTMLField(blank=True, verbose_name='tinymce'),
        ),
    ]
