# Generated by Django 3.2.18 on 2023-04-24 18:24

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0026_auto_20230424_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iti',
            name='file_upload',
        ),
        migrations.RemoveField(
            model_name='iti',
            name='head_image',
        ),
        migrations.AddField(
            model_name='iti',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='iti',
            name='day',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iti',
            name='food',
            field=models.CharField(default={'석식': 'x', '조식': 'x', '중식': 'x'}, max_length=30),
        ),
        migrations.AlterField(
            model_name='iti',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='iti',
            name='item_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.touritem'),
        ),
    ]
