# Generated by Django 3.2.18 on 2023-04-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0028_iti_trans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iti',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='iti',
            name='food',
            field=models.CharField(default={'석식': 'x', '조식': 'x', '중식': 'x'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='iti',
            name='trans',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
