# Generated by Django 3.2.18 on 2023-04-25 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0029_auto_20230425_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iti',
            old_name='item_code',
            new_name='touritem',
        ),
    ]
