# Generated by Django 3.2.18 on 2023-04-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0030_rename_item_code_iti_touritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iti',
            name='food',
            field=models.CharField(default='조식: 호텔식;중식: 현지식;석식: 현지식', max_length=100),
        ),
    ]
