# Generated by Django 3.2.18 on 2023-04-25 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0033_auto_20230425_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itiname',
            options={},
        ),
        migrations.AddField(
            model_name='touritem',
            name='iti_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.itiname'),
        ),
    ]
