# Generated by Django 3.2.18 on 2023-04-26 02:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0034_auto_20230425_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='itiname',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itiname',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
