# Generated by Django 3.2.18 on 2023-04-26 03:14

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0035_auto_20230426_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareItiName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShareIti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('trans', models.CharField(blank=True, max_length=100)),
                ('content', tinymce.models.HTMLField(blank=True)),
                ('food', models.CharField(default='조식: 호텔식;중식: 현지식;석식: 현지식', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('iti_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.shareitiname')),
            ],
        ),
    ]
