# Generated by Django 3.2.18 on 2023-04-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0036_shareiti_shareitiname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touritem',
            old_name='air_sync',
            new_name='share_air_chk',
        ),
        migrations.RemoveField(
            model_name='touritem',
            name='confirm',
        ),
        migrations.AddField(
            model_name='touritem',
            name='iti_confirm_chk',
            field=models.BooleanField(default=False, help_text='확정시, 전용일정. 로직 충돌'),
        ),
        migrations.AddField(
            model_name='touritem',
            name='share_iti_chk',
            field=models.BooleanField(default=True, help_text='해당 상품만 일정 수정시, 체크해제, 다시 체크하면 기본 일정표로.'),
        ),
    ]
