# Generated by Django 3.2.18 on 2023-04-28 16:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0042_auto_20230428_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockitem',
            name='name',
        ),
        migrations.AddField(
            model_name='blockitem',
            name='air_code',
            field=models.CharField(default=django.utils.timezone.now, max_length=2, verbose_name='항공 코드'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockitem',
            name='airline',
            field=models.CharField(blank=True, max_length=20, verbose_name='항공사'),
        ),
        migrations.AddField(
            model_name='blockitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockitem',
            name='d_city1',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='blockitem',
            name='d_city2',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='blockitem',
            name='d_date1',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='blockitem',
            name='d_daychange',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='blockitem',
            name='d_fltno',
            field=models.CharField(default='KE0000', max_length=6, verbose_name='출발 편명'),
        ),
        migrations.AddField(
            model_name='blockitem',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blockitem',
            name='name_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tour.block'),
        ),
        migrations.AddField(
            model_name='blockitem',
            name='price',
            field=models.IntegerField(default=0, help_text='미입력시 0. 문의', verbose_name='숫자'),
        ),
        migrations.AddField(
            model_name='blockitem',
            name='r_daychange',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='blockitem',
            name='r_fltno',
            field=models.CharField(default='KE0000', max_length=6, verbose_name='리턴 편명'),
        ),
        migrations.AddField(
            model_name='blockitem',
            name='stay',
            field=models.IntegerField(default=5),
        ),
    ]
