# Generated by Django 3.2.18 on 2023-04-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0043_auto_20230428_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockitem',
            name='air_code',
        ),
        migrations.RemoveField(
            model_name='blockitem',
            name='airline',
        ),
    ]
