# Generated by Django 3.2.18 on 2023-04-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0044_auto_20230428_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockitem',
            name='d_city1',
            field=models.CharField(blank=True, default='ICN', max_length=3),
        ),
        migrations.AlterField(
            model_name='blockitem',
            name='d_city2',
            field=models.CharField(blank=True, default='CJU', max_length=3),
        ),
    ]
