# Generated by Django 3.2.18 on 2023-04-29 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0045_auto_20230428_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockitem',
            name='name_fk',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='BlockItem',
        ),
    ]
