# Generated by Django 3.2.18 on 2023-04-29 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0046_auto_20230429_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touritem',
            name='basic_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touritem', to='tour.basiccode'),
        ),
    ]
