# Generated by Django 3.2.18 on 2023-04-29 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0047_alter_touritem_basic_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basiccode',
            old_name='basic_code',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='touritem',
            old_name='basic_code',
            new_name='basiccode_fk',
        ),
    ]
