# Generated by Django 3.2.18 on 2023-04-30 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0048_auto_20230429_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touritem',
            name='basiccode_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='touritem_rn', to='tour.basiccode'),
        ),
    ]
