# Generated by Django 3.2.18 on 2023-04-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0050_alter_touritem_basiccode_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touritem',
            name='etc',
        ),
    ]
