# Generated by Django 3.2.18 on 2023-04-30 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0051_remove_touritem_etc'),
    ]

    operations = [
        migrations.AddField(
            model_name='touritem',
            name='d_date2',
            field=models.DateField(default=datetime.date(2000, 1, 2)),
        ),
    ]
