# Generated by Django 3.2.18 on 2023-05-02 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0052_touritem_d_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touritem',
            name='d_daychange',
        ),
        migrations.RemoveField(
            model_name='touritem',
            name='r_daychange',
        ),
        migrations.AddField(
            model_name='touritem',
            name='r_date1',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='touritem',
            name='r_date2',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
