# Generated by Django 3.2.18 on 2023-05-02 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0053_auto_20230502_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touritem',
            name='r_date1',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='touritem',
            name='r_date2',
            field=models.DateField(default=datetime.date(2000, 1, 2)),
        ),
    ]
