# Generated by Django 3.2.18 on 2023-05-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0054_auto_20230502_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='touritem',
            name='d_daychange',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='touritem',
            name='r_daychange',
            field=models.IntegerField(default=1),
        ),
    ]
