# Generated by Django 3.2.18 on 2023-05-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0055_auto_20230502_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touritem',
            name='d_daychange',
        ),
        migrations.RemoveField(
            model_name='touritem',
            name='r_daychange',
        ),
    ]
