# Generated by Django 3.2.18 on 2023-05-02 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0057_remove_touritem_stay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touritem',
            name='d_city1',
            field=models.CharField(blank=True, default='ICN', max_length=3),
        ),
        migrations.AlterField(
            model_name='touritem',
            name='d_city2',
            field=models.CharField(blank=True, default='VTE', max_length=3),
        ),
        migrations.AlterField(
            model_name='touritem',
            name='d_time1',
            field=models.TimeField(default=datetime.time(12, 12)),
        ),
        migrations.AlterField(
            model_name='touritem',
            name='d_time2',
            field=models.TimeField(default=datetime.time(12, 12)),
        ),
        migrations.AlterField(
            model_name='touritem',
            name='r_city1',
            field=models.CharField(blank=True, default='VTE', max_length=3),
        ),
        migrations.AlterField(
            model_name='touritem',
            name='r_city2',
            field=models.CharField(blank=True, default='ICN', max_length=3),
        ),
        migrations.AlterField(
            model_name='touritem',
            name='r_date1',
            field=models.DateField(default=datetime.date(2000, 1, 5)),
        ),
        migrations.AlterField(
            model_name='touritem',
            name='r_date2',
            field=models.DateField(default=datetime.date(2000, 1, 6)),
        ),
        migrations.AlterField(
            model_name='touritem',
            name='r_time1',
            field=models.TimeField(default=datetime.time(12, 12)),
        ),
        migrations.AlterField(
            model_name='touritem',
            name='r_time2',
            field=models.TimeField(default=datetime.time(12, 12)),
        ),
    ]
