# Generated by Django 3.2.19 on 2023-05-07 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0059_block_blockitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touritem',
            name='author',
        ),
    ]
