# Generated by Django 3.2.19 on 2023-05-07 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0060_remove_touritem_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='touritem',
            name='blockitem_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tour.blockitem'),
        ),
    ]
