# Generated by Django 3.2.19 on 2023-05-08 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_block_blockitem'),
        ('tour', '0061_touritem_blockitem_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockitem',
            name='name_fk',
        ),
        migrations.AlterField(
            model_name='touritem',
            name='blockitem_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='block.blockitem'),
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='BlockItem',
        ),
    ]
