# Generated by Django 3.2.19 on 2023-05-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('check', models.IntegerField(default=0)),
                ('date', models.CharField(max_length=50, null=True)),
                ('user', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
